export const GET_PRODUCT_STOCK = 'GET_PRODUCT_STOCK';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_ALL_PRODUCT_INFO = 'GET_ALL_PRODUCT_INFO';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const SET_LOADING = 'SET_LOADING';
